import styles from './page.module.css';
import Hero from '@/components/hero/Hero';
import CategoryLinks from '@/components/CategoryLinks/CategoryLinks';
import FeaturedProducts from '@/components/FeaturedProducts/FeaturedProducts';

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles.main}>
      <Hero />
      <CategoryLinks />
      <FeaturedProducts />
    </main>
  );
}
