import Image from 'next/image';
import styles from './page.module.css';
import Hero from '@/components/hero/Hero';

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles.main}>
      <Hero />
      <div>I am the home page</div>
    </main>
  );
}
