import styles from './page.module.css';
import getCategorySKUS from '@/lib/getCategorySKU';

import CategoryHeader from '@/components/CategoryHeader/CategoryHeader';
import CategoryLinks from '@/components/CategoryLinks/CategoryLinks';
import About from '@/components/About/About';
import CategorySKU from '@/components/CategorySKU/CategorySKU';
import CategorySKUS from '@/components/CategorySKUS/CategorySKUS';

export const metadata = {
  title: 'Headphones',
  description: 'Generated by create next app',
};

export default function HeadphonesPage() {
  const skus = getCategorySKUS('headphones');
  console.log(skus);

  return (
    <div>
      <CategoryHeader name={'HEADPHONES'} />
      <CategorySKUS category="headphones" />
      <CategoryLinks />
      <About />
    </div>
  );
}
