import getCategorySKUS from '@/lib/getCategorySKU';

import CategoryHeader from '@/components/CategoryHeader/CategoryHeader';
import CategoryLinks from '@/components/CategoryLinks/CategoryLinks';
import About from '@/components/About/About';
import CategorySKU from '@/components/CategorySKU/CategorySKU';

export const metadata = {
  title: 'Headphones',
  description: 'Generated by create next app',
};

export default function HeadphonesPage() {
  const skus = getCategorySKUS('headphones');
  console.log(skus);

  return (
    <div>
      <CategoryHeader name={'HEADPHONES'} />
      <CategoryLinks />
      {skus.map((sku, index) => {
        return (
          <CategorySKU
            key={sku.id}
            index={index}
            name={sku.name}
            slug={sku.slug}
            description={sku.description}
            images={sku.categoryImage}
          />
        );
      })}
      <About />
    </div>
  );
}
